services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_NAME: Drone-BE
      ENV: local
      DEBUG: "true"
      DATABASE_URL: sqlite:///./drone.db
    volumes:
      - ./app:/code/app
